### ISSUE TITLE
Register Failed

### ISSUE THREAD

**Issue by LengYuna** [SDUOJ/OnlineJudge#2]
**Describe the bug**
Register failed.
The admin failed to add new users.

**To Reproduce**

1. Go to Register page
2. Finish inputing the information
3. Click on 'register'

![](https://github.com/LengYuna/Algorithm/blob/master/1.png)
![](https://github.com/LengYuna/Algorithm/blob/master/2.png)

**Environment:**

 - OS: Ubuntu 20.04
 - CPU: [6 Core]
 - RAM: [8 GB]
 - Disk: [900 GB]
 - Docker Version: [20.10.0]
 - Docker-Compose Version: [1.27.4]

**Comment by zhangt2333** [comment]
@LengYuna 
Thank you for your feedback. The document is not perfect complete now.

You can setting your own email sender by:
1. http://your-ip:8848/nacos. (If access failed, you should update your ECS _network security group_)
2. login with `sduoj` as account and `sduoj` as password
3. edit `user-service.yml`, update the `mail` part with your own _Email Authorization Code_
![image](https://user-images.githubusercontent.com/35210901/102214785-c3647000-3f13-11eb-87a7-91b7524799c9.png)
![image](https://user-images.githubusercontent.com/35210901/102214933-f0188780-3f13-11eb-96cf-d71b8c4d4b34.png)

**Comment by zhangt2333** [comment]
@LengYuna 
I remembered something, some ECS closed `port 25` so that it was impossible to use `smtp` for mail delivery

**Comment by LengYuna** [comment]
@zhangt2333 
Thanks a lot, I'll try later.
